import type { LearningTopic, LearningQuestion } from './course';

interface ExtraSeed {
  id: string; month: number; title: string; ru: string; why: string; trigger: string;
  flow: string[]; code: string; question: string; answer: string; wrong: [string, string]; source: string;
}

const seeds: ExtraSeed[] = [
  { id:'local-practice', month:1, title:'Local React practice', ru:'Практика с локальным state',
    why:'Барои Todo аввал store даркор нест. Рӯйхат, матни input ва id-и интихобшуда дар ҳамон компонент меистанд. Барои Add spread, Delete filter ва Edit map истифода кун.',
    trigger:'Клик handler-ро ҷеғ мезана. Худи render Delete намекунад. Ягон HTTP запрос фиристода намешавад.',
    flow:['items = [1, 2, 3]','Клик ба Delete-и id=2','handleDelete(2)','filter: 1 ва 3 мемонанд','setItems массиви навро мегира','React UI-ро бо [1, 3] нав мекунад'],
    code:'import { useState } from "react";\n\nexport default function Todo() {\n  const [items, setItems] = useState([{ id: 1, name: "React" }, { id: 2, name: "Props" }]);\n\n  function handleDelete(id) {\n    setItems(items.filter(item => item.id !== id));\n  }\n\n  return items.map(item => (\n    <button key={item.id} onClick={() => handleDelete(item.id)}>\n      {item.name}\n    </button>\n  ));\n}',
    question:'Дар Todo-и локалӣ Delete кадом запросро мефиристад?', answer:'Ҳеҷ запрос. filter массиви нав месозад ва setItems state-ро нав мекунад.', wrong:['Ҳатман HTTP DELETE ба сервер меравад.','React тамоми сайтро reload мекунад.'], source:'https://react.dev/learn/updating-arrays-in-state' },
  { id:'tooling', month:1, title:'Vite, bundlers and MUI', ru:'Vite, сборщики и MUI',
    why:'Vite сервери development ва build медиҳад. MUI компонентҳои интерфейс медиҳад. React state ва render-ро идора мекунад. Вазифаи ин се чиз як хел нест.',
    trigger:'npm run dev серверро оғоз мекунад; edit-и файл HMR-ро фаъол мекунад. Клик ба Button танҳо handler-и додагиатро иҷро мекунад.',
    flow:['package.json: scripts-ро бин','npm install дар папкаи проект','npm run dev','src/App.jsx кушода мешавад','Файлро тағйир деҳ','Барои production: npm run build'],
    code:'import { Button, Stack } from "@mui/material";\nimport { useState } from "react";\n\nexport default function App() {\n  const [count, setCount] = useState(0);\n  function handleAdd() { setCount(count + 1); }\n  return <Stack sx={{ gap: "16px" }}>\n    <Button onClick={handleAdd} sx={{ textTransform: "none" }}>{count}</Button>\n  </Stack>;\n}',
    question:'Vite ва React як вазифа доранд?', answer:'Не. Vite dev/build-ро омода мекунад; React компонентҳо ва UI-ро render мекунад.',wrong:['Ҳа, ҳарду database месозанд.','MUI ҷойи React state-ро мегирад.'],source:'https://vite.dev/guide/' },
  { id:'ui-libraries', month:1, title:'UI libraries and accessibility', ru:'UI-библиотеки и доступность',
    why:'MUI, Antd, shadcn ва Headless UI роҳҳои гуногуни сохтани UI ҳастанд. Барои як машқи сода ҳамаи онҳоро якҷо насб намекунем. HTML-и маънодор, label ва focus аз ранги зебо муҳимтаранд.',
    trigger:'Tab focus-ро ба тугма мебарад. Enter ё клик onClick-ро иҷро мекунад. Label ба input номи фаҳмо медиҳад.',
    flow:['Як UI library интихоб кун','Input бо label соз','Бо Tab гузар','Бо Enter тугмаро санҷ','Focus-ро намоён нигоҳ дор'],
    code:'import { TextField, Button, Stack } from "@mui/material";\n\nexport default function SearchForm() {\n  return <Stack component="form" sx={{ gap: "16px" }}>\n    <TextField label="Ҷустуҷӯ" name="search" />\n    <Button type="submit" sx={{ textTransform: "none" }}>Ҷустуҷӯ</Button>\n  </Stack>;\n}',question:'Input-и бе label барои чӣ мушкил мешавад?',answer:'Корбар ва screen reader намефаҳманд, ки дар ин майдон чӣ нависанд.',wrong:['Label React-ро ба backend табдил медиҳад.','Input ҳатман бояд animation дошта бошад.'],source:'https://mui.com/material-ui/react-text-field/' },
  { id:'local-persistence', month:1, title:'Theme, language and localStorage', ru:'Тема, язык и localStorage',
    why:'State дар хотира аст; баъди F5 аз нав оғоз мешавад. localStorage як нусхаи string-ро дар ҳамин браузер нигоҳ медорад. Ин global state ё синхронизацияи телефон нест.',
    trigger:'Ҳангоми mount қимати пешина хонда мешавад. Клик ҳам state ва ҳам нусхаи localStorage-ро иваз мекунад. Барои i18n калид ба луғати забони интихобшуда меравад; slider аз activeId вобаста мешавад.',
    flow:['Mount','localStorage.getItem','Қимати хондашуда ба state','Клик theme-ро иваз мекунад','setTheme','localStorage.setItem','F5 → қимат аз нав хонда мешавад'],
    code:'import { useEffect, useState } from "react";\n\nexport default function ThemeButton() {\n  const [theme, setTheme] = useState("light");\n  useEffect(() => {\n    setTheme(localStorage.getItem("theme") || "light");\n  }, []);\n  function handleTheme() {\n    const nextTheme = theme === "light" ? "dark" : "light";\n    setTheme(nextTheme);\n    localStorage.setItem("theme", nextTheme);\n  }\n  return <button onClick={handleTheme}>{theme}</button>;\n}',question:'localStorage маълумотро байни компютер ва телефон худаш мефиристад?',answer:'Не. Маълумот ба origin ва браузери ҳамин дастгоҳ вобаста аст.',wrong:['Ҳа, ҳамин маънои global state аст.','useState худаш localStorage-ро нав мекунад.'],source:'https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage' },
  { id:'react-hook-form', month:2, title:'React Hook Form', ru:'React Hook Form', why:'register input-ро ба форма мепайвандад. handleSubmit аввал validation-ро мегузаронад. Агар field нодуруст бошад, onSubmit иҷро намешавад; errors-ро назди ҳамон field нишон медиҳем.', trigger:'submit → validation → onSubmit танҳо барои маълумоти дуруст. Хатои API аз хатои field ҷудо аст.',
    flow:['register("name")','Корбар матн менависад','Submit','required месанҷад','Холӣ → errors.name','Дуруст → onSubmit(values)'],
    code:'import { useForm } from "react-hook-form";\n\nexport default function NameForm() {\n  const { register, handleSubmit, formState: { errors } } = useForm();\n  function onSubmit(values) { console.log(values); }\n  return <form onSubmit={handleSubmit(onSubmit)}>\n    <input aria-label="Ном" {...register("name", { required: true })} />\n    {errors.name && <p>Номро навис</p>}\n    <button type="submit">Сабт</button>\n  </form>;\n}',question:'Дар RHF handleSubmit кай onSubmit-ро иҷро мекунад?',answer:'Баъди гузаштани validation бо values-и форма.',wrong:['Дар ҳар render, ҳатто бе submit.','Фақат баъди reload шудани сайт.'],source:'https://react-hook-form.com/get-started' },
  { id:'formik', month:2, title:'Formik and Yup', ru:'Formik и Yup', why:'Formik values, errors ва touched-ро нигоҳ медорад. Yup қоидаи маълумотро месанҷад. touched нишон медиҳад, ки корбар аллакай бо field кор кардааст; аз ҳамин сабаб errors-ро баъди ламс кардан нишон додан мумкин.', trigger:'onChange values-ро, onBlur touched-ро нав мекунад; submit validation ва баъд onSubmit-ро иҷро мекунад.',
    flow:['initialValues','handleChange','values.name нав мешавад','handleBlur → touched.name','Yup required','handleSubmit → onSubmit'],
    code:'import { useFormik } from "formik";\nimport * as Yup from "yup";\n\nexport default function NameForm() {\n  const formik = useFormik({\n    initialValues: { name: "" },\n    validationSchema: Yup.object({ name: Yup.string().required("Номро навис") }),\n    onSubmit(values) { console.log(values); },\n  });\n  return <form onSubmit={formik.handleSubmit}>\n    <input name="name" aria-label="Ном" value={formik.values.name} onChange={formik.handleChange} onBlur={formik.handleBlur} />\n    {formik.touched.name && <p>{formik.errors.name}</p>}\n    <button type="submit">Сабт</button>\n  </form>;\n}',question:'touched дар Formik чиро нишон медиҳад?',answer:'Корбар бо кадом field аллакай кор кардааст, масалан аз input баромадааст.',wrong:['Дар database чанд user ҳаст.','Кадом request ҳатман муваффақ мешавад.'],source:'https://formik.org/docs/tutorial' },
  { id:'typescript', month:2, title:'TypeScript for React', ru:'TypeScript для React', why:'TypeScript пеш аз иҷро shape-и props ва state-ро месанҷад. type Todo = { id: number; name: string } мегӯяд, ки объект чӣ дорад. Ин validation-и ҷавоби API дар runtime нест.', trigger:'Type checker ҳангоми санҷиш/build. Дар браузер type тоза мешавад; click ва render мисли JavaScript кор мекунанд.',
    flow:['type Todo','Props: item ва onDelete','onDelete(id: number)','Клик id-ро мефиристад','Parent массивро нав мекунад','TypeScript пешакӣ string id-ро хато мегӯяд'],
    code:'type Todo = { id: number; name: string };\ntype Props = { item: Todo; onDelete: (id: number) => void };\n\nexport default function TodoCard({ item, onDelete }: Props) {\n  return <button onClick={() => onDelete(item.id)}>{item.name}</button>;\n}',question:'TypeScript оё ҷавоби API-ро дар runtime худаш месанҷад?',answer:'Не. Type дар runtime нест; маълумоти берунаро алоҳида validate мекунем.',wrong:['Ҳа, type ҳама response-ро автоматӣ ислоҳ мекунад.','TypeScript ҳама хатои мантиқиро пешгирӣ мекунад.'],source:'https://www.typescriptlang.org/docs/handbook/react.html' },
  { id:'data-fetching', month:2, title:'Requests, loading and errors', ru:'Запросы, загрузка и ошибки', why:'Запрос вақти иҷро дорад ва метавонад хато диҳад. Се чизро алоҳида нигоҳ дор: data, loading, error. Агар search зуд иваз шавад, ҷавоби кӯҳна набояд натиҷаи навро рӯпӯш кунад.', trigger:'Effect баъди mount ё тағйири dependency запросро оғоз мекунад. Cleanup-и мисол ҷавоби кӯҳнаро нодида мегирад; request-ро ҳатман қатъ намекунад.',
    flow:['search тағйир ёфт','cleanup-и effect-и пешина','loading=true','GET бо search','response.ok санҷида мешавад','Ҷавоби нав → setItems','Хато → setError','finally → loading=false'],
    code:'import { useEffect, useState } from "react";\n\nexport default function ProductList({ url }: { url: string }) {\n  const [items, setItems] = useState<{ id: number; name: string }[]>([]);\n  const [error, setError] = useState("");\n  useEffect(() => {\n    let ignore = false;\n    async function getData() {\n      try {\n        const response = await fetch(url);\n        if (!response.ok) throw new Error("Request failed");\n        const data = await response.json();\n        if (!ignore) setItems(data);\n      } catch { if (!ignore) setError("Хатои запрос"); }\n    }\n    getData();\n    return () => { ignore = true; };\n  }, [url]);\n  return <div>{error || items.map(item => <p key={item.id}>{item.name}</p>)}</div>;\n}',question:'Ҷавоби search-и кӯҳна дертар биёяд, чӣ хатар дорад?',answer:'Метавонад натиҷаи search-и навро рӯпӯш кунад; ҷавоби кӯҳнаро ignore ё request-ро abort мекунем.',wrong:['React худаш ҳамеша request-ҳоро бо тартиб мегузорад.','Dependency array лозим нест.'],source:'https://react.dev/reference/react/useEffect' },
  { id:'auth-flow', month:2, title:'Authentication flow', ru:'Авторизация в приложении', why:'Protected route танҳо UI-ро пинҳон мекунад. Сервер бояд session ва ҳуқуқи ҳар request-ро худаш санҷад. То маълум шудани session loading нишон деҳ; redirect-и бармаҳал накун.', trigger:'Submit login → сервер session месозад. Баъд ҳар амали ҳифзшуда дар сервер аз нав иҷозат санҷида мешавад.',
    flow:['Формаи login','Submit','Сервер маълумотро месанҷад','Session','Дархости ҳифзшуда','401: login лозим','403: иҷозат нест'],code:'// Мантиқи UI; иҷозати воқеӣ дар сервер санҷида мешавад.\nfunction Account({ status, user }) {\n  if (status === "loading") return <p>Loading...</p>;\n  if (!user) return <p>Login лозим</p>;\n  return <h1>{user.name}</h1>;\n}',question:'Protected route-и React backend-ро ҳам муҳофизат мекунад?',answer:'Не. Backend бояд session ва иҷозати request-ро худаш санҷад.',wrong:['Ҳа, пинҳон кардани Button кофӣ аст.','userId-и фиристодаи браузер ҳамеша боэътимод аст.'],source:'https://nextjs.org/docs/app/guides/authentication' },
  { id:'next-rendering', month:3, title:'SSR, CSR, SSG and ISR', ru:'SSR, CSR, SSG и ISR', why:'CSR қисми асосии UI-ро дар браузер месозад. SSR натиҷаро барои request дар сервер омода мекунад. SSG пешакӣ месозад; ISR нусхаи пешакӣ сохтаро нав мекунад. Интихоб аз тозагии data ва хусусияти page вобаста аст.',trigger:'SSR аз request, CSR аз browser render, SSG аз build/pre-render ва revalidation аз қоидаи cache фаъол мешавад.',flow:['URL кушода шуд','Route муайян шуд','Cache ё render-и сервер','HTML ва RSC payload','Браузер UI-ро нишон медиҳад','Қисми интерактивӣ hydrate мешавад'],code:'export default function AboutPage() {\n  return <main><h1>Дар бораи проект</h1></main>;\n}',question:'SSR ва SSG аз чӣ фарқ мекунанд?',answer:'SSR натиҷаро барои request месозад; SSG пешакӣ омода мекунад.',wrong:['Ҳарду танҳо дар браузер иҷро мешаванд.','SSG ҳар кликро ба database менависад.'],source:'https://nextjs.org/docs/app/getting-started/server-and-client-components' },
  { id:'next-routing', month:3, title:'App Router and layouts', ru:'App Router и layout',why:'Папка segment-и URL аст. page.tsx UI-и route-ро медиҳад; layout.tsx қисми умумиро нигоҳ медорад. loading.tsx вақти интизорӣ ва error.tsx хатои қисми route-ро нишон медиҳанд.',trigger:'Клик ба Link → navigation. Next route-и мувофиқро мегирад; layout-и муштарак метавонад нигоҳ дошта шавад.',flow:['app/layout.tsx','app/page.tsx → /','app/products/page.tsx → /products','Link','loading дар интизорӣ','page-и нав'],code:'// app/products/page.tsx\nimport Link from "next/link";\n\nexport default function ProductsPage() {\n  return <main><h1>Маҳсулот</h1><Link href="/">Ба асосӣ</Link></main>;\n}',question:'Файли app/products/page.tsx кадом URL-ро медиҳад?',answer:'/products',wrong:['/app/products/page.tsx','Танҳо баъди useEffect route пайдо мешавад.'],source:'https://nextjs.org/docs/app/getting-started/layouts-and-pages' },
  { id:'next-components', month:3, title:'Server and Client Components', ru:'Серверные и клиентские компоненты',why:'Page ва layout одатан Server Component ҳастанд. Барои useState, handler ва browser API Client Component лозим мешавад. use client сарҳади module graph аст; тамоми page-ро бе зарурат client накун.',trigger:'Сервер data ва UI-и сервериро омода мекунад. Handler-и интерактивӣ баъди hydration дар браузер кор мекунад.',flow:['Server Component data мегирад','Props-и serializable','Client Component','Hydration','Клик','setState → render'],code:'"use client";\nimport { useState } from "react";\n\nexport default function Counter() {\n  const [count, setCount] = useState(0);\n  return <button onClick={() => setCount(count + 1)}>{count}</button>;\n}',question:'Барои useState ва onClick дар App Router чӣ лозим аст?',answer:'Client Component бо сарҳади use client.',wrong:['Ҳатман database дар браузер.','Дар ҳар файл use server.'],source:'https://nextjs.org/docs/app/getting-started/server-and-client-components' },
  { id:'next-data', month:3, title:'Data fetching in Next.js', ru:'Данные в Next.js',why:'Дар Server Component data-ро бо await гирифтан мумкин. Барои loading ва error рафторро пешакӣ муайян кун. Cache-и framework-ро бо state-и браузер як чиз ҳисоб накун; версия ва cache policy-ро санҷ.',trigger:'Route render мешавад → async function data мегирад → UI бармегардад. Request-и сервер дар Network-и браузер ҳамчун fetch-и ҷудо ҳатман намоён нест.',flow:['Route request','Server Component','fetch ё database query','response санҷида мешавад','Props ё JSX','UI'],code:'// Функсияи ёрирасон: url бояд аз API-и воқеии проект биёяд.\nasync function getData(url: string) {\n  const response = await fetch(url, { cache: "no-store" });\n  if (!response.ok) throw new Error("Request failed");\n  return response.json();\n}',question:'Server Component барои гирифтани data ҳатман useEffect мехоҳад?',answer:'Не. Он метавонад data-ро бо async/await дар сервер гирад.',wrong:['Ҳа, бе useEffect сервер кор намекунад.','Server Component бояд localStorage истифода барад.'],source:'https://nextjs.org/docs/app/getting-started/fetching-data' },
  { id:'next-blog', month:3, title:'Static blog and MDX', ru:'Статический блог и MDX',why:'Матни мақола аз state-и интерактивӣ ҷудо аст. Барои blog route-и /blog/[slug] соз; slug-и номаълум 404 диҳад. MDX матн ва компонентро якҷо медиҳад, вале танҳо манбаи боэътимодро compile кун.',trigger:'Клик ба мақола ё F5 → slug аз URL → мақолаи мувофиқ. location.state барои мустақил кушодани саҳифа кофӣ нест.',flow:['Рӯйхати мақолаҳо','Link бо slug','URL','Ҷустуҷӯи мақола','Нест → notFound','Ҳаст → content'],code:'// app/blog/[slug]/page.tsx\nimport { notFound } from "next/navigation";\nconst posts = [{ slug: "react", title: "React", body: "Оғози омӯзиш" }];\n\nexport default async function PostPage({ params }: { params: Promise<{ slug: string }> }) {\n  const { slug } = await params;\n  const post = posts.find(item => item.slug === slug);\n  if (!post) notFound();\n  return <article><h1>{post.title}</h1><p>{post.body}</p></article>;\n}',question:'Detail page баъди F5 data-ро аз куҷо муайян кунад?',answer:'Аз URL params ва манбаи data; на танҳо аз state-и navigation.',wrong:['Аз тугмаи пешинаи пахшшуда ҳатман.','F5-ро манъ мекунем.'],source:'https://nextjs.org/docs/app/api-reference/file-conventions/dynamic-routes' },
  { id:'next-api', month:3, title:'Route Handlers', ru:'Route Handlers',why:'route.ts request мегирад ва Response медиҳад. HTTP method, body ва status-ро аниқ навис. Маълумоти браузерро validate кун. Агар data сабт нашуда бошад, success нагӯ.',trigger:'HTTP GET/POST ба URL-и route. Ин endpoint аст; React mount ба худӣ худ онро иҷро намекунад.',flow:['Браузер request мефиристад','Route Handler','JSON хонда мешавад','Validation','Амали сервер','Response бо status','Браузер result-ро мегирад'],code:'// app/api/echo/route.ts — мисоли бе database\nexport async function POST(request: Request) {\n  const body = await request.json();\n  if (typeof body.name !== "string" || !body.name.trim()) {\n    return Response.json({ error: "Name required" }, { status: 400 });\n  }\n  return Response.json({ name: body.name.trim() });\n}',question:'Route Handler чӣ бармегардонад?',answer:'Response: body, status ва headers-и HTTP.',wrong:['Ҳамеша React JSX.','Танҳо useState.'],source:'https://nextjs.org/docs/app/getting-started/route-handlers' },
  { id:'next-auth', month:3, title:'NextAuth and sessions', ru:'NextAuth и session',why:'Auth library раванди воридшавӣ ва session-ро осон мекунад. Authentication мегӯяд кӣ ҳастӣ; authorization мегӯяд чӣ кор карда метавонӣ. Барои update-и чужой record session-и дуруст ҳам кофӣ нест — ownership санҷида мешавад.',trigger:'Воридшавӣ session месозад. Route-и ҳифзшуда пеш аз хондан ё навиштан session-ро аз сервер месанҷад.',flow:['Sign in','Provider','Session','Request','Session verification','Ownership check','Амали иҷозатдодашуда'],code:'// Мантиқи иҷозат, қисми мустақили TypeScript\ntype Session = { userId: string } | null;\n\nfunction canEdit(session: Session, ownerId: string) {\n  if (!session) return false;\n  return session.userId === ownerId;\n}',question:'Session ҳаст: оё ҳар record-ро edit кардан мумкин?',answer:'Не. Илова ба session, ҳуқуқ ва соҳиби record санҷида мешавад.',wrong:['Ҳа, ҳамаи user-ҳо як иҷозат доранд.','userId аз body далели login аст.'],source:'https://authjs.dev/getting-started/session-management/protecting' },
  { id:'database', month:3, title:'Prisma and database', ru:'Prisma и база данных',why:'Database data-ро берун аз хотираи process нигоҳ медорад. Prisma schema ва query-ҳоро бо type мепайвандад. Migration тағйири сохтори database аст; build худ аз худ маълумоти production-ро иваз накунад.',trigger:'Амали сервер → validation → database query. Дар Vercel файли маҳаллии SQLite ҳалли устувори database-и production нест.',flow:['schema','migration','Сервер input-ро validate мекунад','Query','Database','Result','Response'],code:'// schema.prisma — модели омӯзишӣ\nmodel Todo {\n  id        Int     @id @default(autoincrement())\n  name      String\n  completed Boolean @default(false)\n}',question:'Чаро массиви дохили server process database нест?',answer:'Бо restart ё instance-и дигар гум ё ҷудо мешавад; database нигоҳдории устувор медиҳад.',wrong:['Чунки массив map надорад.','Ҳар variable дар Vercel абадӣ мемонад.'],source:'https://www.prisma.io/docs/orm/prisma-schema/data-model/models' },
  { id:'deployment', month:3, title:'Vercel and CI', ru:'Vercel и CI',why:'Build-и локалӣ ва deployment ду санҷиши ҷудо ҳастанд. Дар Vercel framework, build command, environment ва runtime-ро санҷ. Secret-ро дар NEXT_PUBLIC нигоҳ надор: он метавонад ба client bundle равад.',trigger:'Push → build → deployment → URL. Барои гуфтани «кор мекунад» саҳифа ва API-и production-ро кушода санҷ.',flow:['npm run lint','npm run typecheck','npm test','npm run build','Push','Vercel build','URL ва API санҷида мешаванд'],code:'// vercel.json\n{\n  "framework": "nextjs",\n  "buildCommand": "npm run build"\n}',question:'NEXT_PUBLIC_ барои secret мувофиқ аст?',answer:'Не. Ин prefix барои қиматҳои ба браузер дастрас аст.',wrong:['Ҳа, номи дароз secret-ро пинҳон мекунад.','Secret-ро дар component навиштан беҳтар аст.'],source:'https://nextjs.org/docs/app/guides/environment-variables' },
  { id:'fullstack', month:3, title:'Full-stack project', ru:'Проект с сервером',why:'Як амали воқеиро пурра соз: форма → validation → request → сервер → database → response → UI. Loading, error ва F5 низ қисми ҳамин вазифаанд. Аз UI-и зебо танҳо маълум намешавад, ки сабт воқеан нигоҳ дошта шудааст.',trigger:'Submit request-ро оғоз мекунад. Танҳо response-и муваффақ UI-ро нав мекунад; баъд GET/F5 нигоҳдории data-ро месанҷад.',flow:['Form','Handler','Request','Server validation ва authorization','Database write','Response','UI update','F5 ва GET барои санҷиш'],code:'async function submitForm(url: string, values: { name: string }) {\n  const response = await fetch(url, {\n    method: "POST",\n    headers: { "Content-Type": "application/json" },\n    body: JSON.stringify(values),\n  });\n  if (!response.ok) throw new Error("Save failed");\n  return response.json();\n}',question:'Тугма success нишон дод: чӣ тавр persistence-ро санҷем?',answer:'Баъди сабти сервер F5 ё GET мекунем ва ҳамон record-ро аз database мебинем.',wrong:['Танҳо ранги сабзи button кофӣ аст.','console.log маънои database save дорад.'],source:'https://nextjs.org/docs/app/guides/backend-for-frontend' },
  { id:'portfolio', month:3, title:'Portfolio and interviews', ru:'Портфолио и интервью',why:'Барои ҳар проект масъала, қисми кори худат, қарори техникӣ ва натиҷаи санҷишро аниқ нишон деҳ. Рақами сохта ё «100% кор мекунад» нанавис. Дар интервью коди худашро бо мисоли пеш/баъд фаҳмон.',trigger:'Корбар проектро мекушояд → вазифаи асосиро санҷида метавонад. Recruiter аз README мефаҳмад, ки чӣ сохтаӣ.',flow:['Масъала','Қарори техникӣ','Коди асосӣ','Демо','Санҷишҳо','Маҳдудиятҳои воқеӣ'],code:'// Намунаи объекти portfolio\nconst project = {\n  id: "todo",\n  title: "Task manager",\n  stack: ["React", "TypeScript"],\n  repository: "",\n  demo: "",\n};',question:'Дар тавсифи проект чӣ нависем?',answer:'Масъала, кори худ, қарорҳои техникӣ, санҷиш ва маҳдудиятҳои воқеӣ.',wrong:['Фақат рӯйхати ҳамаи library-ҳои дунё.','Натиҷаҳое, ки санҷида нашудаанд.'],source:'react-roadmap-tracker (1) (1).html' },
  { id:'project-planning', month:3, title:'Project planning', ru:'План проекта',why:'Пеш аз код user flow ва data contract навис. Ба AI scope-и маҳдуд, files ва натиҷаи интизориро деҳ. Ҳар edit-ро бо diff ва санҷиш бин; матни AI далели кор кардани код нест.',trigger:'Талабот → нақша → вазифаи хурд → код → санҷиш. Агар контракт маълум нест, пеш аз тахмин кардани field онро равшан кун.',flow:['Талабот','Route ва data','Як user flow','Файлҳои зарурӣ','Implementation','Tests','Review'],code:'// Нақшаи як амали user\nconst task = {\n  action: "Delete",\n  input: "id-и item",\n  success: "item аз рӯйхат нест мешавад",\n  failure: "item мемонад, error намоён мешавад",\n};',question:'Ба AI пеш аз иҷрои тағйир чӣ контекст медиҳем?',answer:'Масъала, source-и воқеӣ, маҳдудият, файлҳо ва натиҷаи санҷиш.',wrong:['Фақат «ҳамаашро хуб кун».','Ҳама token ва secret-ҳои проект.'],source:'react-roadmap-tracker (1) (1).html' },
  { id:'ai-workflow', month:2, title:'AI tools and code review', ru:'AI-инструменты и ревью кода',why:'AI барои фаҳмидани файл, сохтани нақша ва edit ёрӣ медиҳад. Ту scope, версия ва натиҷаро месанҷӣ. Context window ҷойи маҳдуди маълумоти фаъол аст; файлҳои заруриро аниқ нишон деҳ.',trigger:'Промти мушаххас → хондани source → edit → diff → build/test → қарор. Барои review хатои исботшуда аз пешниҳоди услуб ҷудо мешавад.',flow:['Талаботро навис','Файлҳои воқеиро диҳ','Нақшаро бин','Edit','Diff','Build/test','Кодро худат фаҳмон'],code:'// Намунаи супориши мушаххас\nconst request = {\n  file: "src/pages/Todo.jsx",\n  change: "Delete бо filter",\n  preserve: "UI ва дигар handler-ҳо",\n  check: "id=2 аз [1,2,3] → [1,3]",\n};',question:'Коди AI кай санҷидашуда ҳисоб мешавад?',answer:'Вақте source ва натиҷаи иҷро бо санҷиши мувофиқ тасдиқ шудаанд.',wrong:['Вақте AI «тайёр» менависад.','Вақте код дароз ва мураккаб аст.'],source:'react-roadmap-tracker (1) (1).html' },
];

export const EXTRA_TOPICS: LearningTopic[] = seeds.map(seed => ({
  id: seed.id, month: seed.month, title: seed.title, titleRu: seed.ru,
  explanation: [{title:'Чӣ кор мекунад?', text:seed.why},{title:'Аз чӣ оғоз мешавад?', text:seed.trigger}],
  flow: seed.flow, code: [seed.code], questions:[{question:seed.question, answer:seed.answer, deeper:seed.trigger}], source:seed.source,
}));
export const EXTRA_QUESTIONS: LearningQuestion[] = seeds.map(seed => ({
  id:`extra-${seed.id}`, sourceId:seed.id, topicId:seed.id, month:seed.month, group:seed.month,
  question:seed.question, answer:seed.answer, options:[seed.answer,...seed.wrong],
  explanation:seed.why, code:[seed.code], source:seed.source,
}));

const typescriptQuestions = [
  ['Props-ро дар TypeScript чӣ хел менависем?', 'Бо type ё interface майдонҳо ва callback-ҳоро тавсиф мекунем.', 'Ба ҳар props any мемонем.', 'TypeScript props-ро дар database нигоҳ медорад.'],
  ['useState<User | null>(null) чӣ маъно дорад?', 'State метавонад User ё null бошад; пеш аз user.name null-ро месанҷем.', 'State танҳо string қабул мекунад.', 'null худаш user месозад.'],
  ['type Status = "idle" | "loading" чӣ медиҳад?', 'Танҳо ду string-и иҷозатдодашуда; typo-ро type checker мебинад.', 'Ҳар string ва number мумкин аст.', 'Ин HTTP request мефиристад.'],
  ['Фарқи unknown ва any чист?', 'unknown пеш аз истифода санҷиш мехоҳад; any санҷиши type-ро канор мегузорад.', 'unknown ҳамеша number аст.', 'any ҳама validation-и runtime-ро мекунад.'],
  ['Барои event-и input-и React кадом type мувофиқ аст?', 'ChangeEvent<HTMLInputElement>, баъд event.target.value string аст.', 'MouseEvent барои ҳамаи input value-ҳо.', 'Event type лозим шавад, React state кор намекунад.'],
  ['Callback-и onDelete: (id: number) => void чиро мегӯяд?', 'Функсия number мегирад; истифодабаранда натиҷаи return-ро истифода намекунад.', 'Функсия танҳо string қабул мекунад.', 'Функсия ҳатман HTTP DELETE мекунад.'],
  ['name?: string чӣ маъно дорад?', 'name optional аст: метавонад набошад; пеш аз истифода undefined-ро ба назар мегирем.', 'name ҳатман пур аст.', 'Ҳама object optional мешавад.'],
  ['Барои children-и гуногуни React чӣ type истифода мекунем?', 'ReactNode, агар матн, JSX ва дигар children-и иҷозатдодашуда қабул шаванд.', 'Фақат HTMLDivElement.', 'Фақат number[].'],
  ['Дар catch(error) чӣ тавр message-ро бехатар мегирем?', 'Аввал error instanceof Error-ро месанҷем, баъд error.message.', 'Ҳамеша error.data.data.message бе санҷиш.', 'TypeScript ҳар error-ро string мекунад.'],
  ['Файли component бо JSX дар TS-проект чӣ extension дорад?', '.tsx; файли бе JSX метавонад .ts бошад.', 'Ҳама файл ҳатман .jsx аст.', '.json барои component аст.'],
];
typescriptQuestions.forEach((question,index) => EXTRA_QUESTIONS.push({
  id:`ts-${index+1}`,sourceId:`ts-${index+1}`,topicId:'typescript',month:2,group:2,
  question:question[0],answer:question[1],options:question.slice(1),explanation:question[1],code:[],source:'https://www.typescriptlang.org/docs/handbook/react.html',
}));
